apiVersion: backstage.io/v1alpha1
kind: Component
# TODO 해롯, 해롯클라이언트 추가
metadata:
  name: sales-statistics-api
  description: 무신사 매출통계 제공
  annotations:
    musinsa.backstage.io/template: "backstage-component-bitbucket:v0.0.1"
    backstage.musinsa.io/endpoint: https://stat.data.musinsa.com/

  labels:
    env: prd
    project: sales-statistics
    service: sales-statistics
    module: api
  links:
    - title: Wiki(프로젝트 기술 문서)
      url: https://wiki.musinsa.com/pages/viewpage.action?pageId=142842087
    - title: Source Code
      url: https://git.musinsa.com/projects/DS/repos/dataplatform-api/browse/stat
    - title: API Docs
      url: https://stat.data.musinsa.com/stat/docs/statistics-api.html

spec:
  type: api
  lifecycle: production
  owner: group:group:default/데이터플랫폼팀 (데이터본부)
  # 제공중인 API
  providesApis:
    - sales-statistics-api # kind:API 리소스에 대한 이름
