server:
  servlet:
    encoding:
      # Servlet Response UTF-8 config
      charset: UTF-8
      force: true
    # Root Path config
    context-path: /admin

spring:
  profiles:
    # 기본 프로파일을 local 설정
    active: local
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: none

# https://www.baeldung.com/sql-logging-spring-boot
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug
