spring:
  data:
    redis:
      host: dev-harrods-v1-redis.cr5gwi.clustercfg.apn2.cache.amazonaws.com
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev-harrods-mysql-rds.cacpsxq2cnl6.ap-northeast-2.rds.amazonaws.com:3306/harrods
    username: harrods_admin
    password: newjeans1!2@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL8InnoDB 기능 사용
