server:
  servlet:
    encoding:
      # Servlet Response UTF-8 config
      charset: UTF-8
      force: true
    # Root Path config
    context-path: /stat
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    databricks:
      driver-class-name: com.databricks.client.jdbc.Driver
      # TODO Move AWS Secret Manager
      # @see https://docs.databricks.com/integrations/jdbc-odbc-bi.html#configure-the-databricks-odbc-and-jdbc-drivers
      url: jdbc:databricks://musinsa-data-ws.cloud.databricks.com;Port=443;TransportMode=HTTP;HTTPPath=/sql/1.0/warehouses/860d8ab96c5e34fd;PWD=dapiac03c1cb4ac710049a572888106b65e3;UseNativeQuery=1;EnableArrow=0;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

# Custom Properties
custom:
  # Bricklane
  databricks:
    http-connection:
      timeout: 10
      musinsa-data-ws-domain: https://musinsa-data-ws.cloud.databricks.com
      # @see "https://docs.databricks.com/sql/api/queries-dashboards.html#operation/sql-analytics-get-query"
      retrieve-api-path: /api/2.0/preview/sql/queries
      # TODO Move AWS Secret Manager
      authorization-token: Bearer dapiac03c1cb4ac710049a572888106b65e3
    # statistics query id
    stats-query-id:
      daily: a452ce56-849a-4d38-ad2f-244d6fbd972c?o=3626753574208338
      montly: ae97fd63-0b4f-4a10-8b04-5241e83d417d
      partner: 5fda7bef-f0e9-42de-b747-12e06b0cdb92
      brand: 437714c5-01cf-4a4f-9bee-3f3b29d7075a
      brand-partner: 63ecb0c7-6c93-4a66-8045-287519988c1a
      goods: c9ea1cf3-c51f-44d8-b54a-8654267590e7
      ad: 67b5fc73-b66d-4c95-ab29-3af968d83198
      coupon: 208ffd6c-2c11-4f9d-bd39-5fc0540ad5ba
      category: d6991ecf-203e-4c74-8dcb-e38dcfe3e1c8