server:
  servlet:
    encoding:
      # Servlet Response UTF-8 config
      charset: UTF-8
      force: true
    # Root Path config
    context-path: /stat

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

# Custom Properties
custom:
  # Bricklane
  databricks:
    # statistics query id
    stats-query-id:
      daily: a452ce56-849a-4d38-ad2f-244d6fbd972c
      montly: ae97fd63-0b4f-4a10-8b04-5241e83d417d
      partner: 5fda7bef-f0e9-42de-b747-12e06b0cdb92
      brand: 437714c5-01cf-4a4f-9bee-3f3b29d7075a
      brand-partner: 63ecb0c7-6c93-4a66-8045-287519988c1a
      goods: c9ea1cf3-c51f-44d8-b54a-8654267590e7
      ad: 67b5fc73-b66d-4c95-ab29-3af968d83198
      coupon: 208ffd6c-2c11-4f9d-bd39-5fc0540ad5ba
      category: b578e100-29eb-42b0-a1d4-9f852410d5bc
    # for search
    search-query-id:
      brand: 9f2d64da-cb89-4a30-a2cf-07b8fb27bc55
      partner: 663c0430-690c-44e7-9885-e63624f9b125
      tag: 217dc859-e02c-4412-9a43-256a2fa64e1d
