### 쿼리를 생성한다
POST http://localhost:8080/queries
Content-Type: application/json

{
  "template": "SELECT * FROM user WHERE name = {{name}} and age={{age}}",
  "ttl": 20,
  "interval": "* * * *",
  "params": {
    "name": ["peter", "woo"],
    "age": [10, 20]
  }
}

> {%
    client.test("반환값을 검증한다", function() {
        client.assert(response.status === 200, "200 응답");
        client.assert(response.body.length === 2)
        client.assert(response.body[0]["ttl"] === 20)
        client.assert(response.body[0]["interval"] === "* * * *")
        client.assert(response.body[0]["query"] === "SELECT * FROM user WHERE name = peter")
        client.assert(response.body[1]["query"] === "SELECT * FROM user WHERE name = woo")
    });
%}
