server:
  servlet:
    encoding:
      # Servlet Response UTF-8 config
      charset: UTF-8
      force: true
    # Root Path config
    context-path: /client

spring:
  profiles:
    # 기본 프로파일을 local 설정
    active: local
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  data:
    redis:
      port: 6379
