package com.musinsa.stat.sales.domain

/**
 * 정렬값 관리
 */
@Suppress("unused")
enum class OrderBy(
    /**
     * 데이터브릭스 쿼리에 저장된 Alias
     * 주의! 해당 값은 데이터브릭스 쿼리에 적용된 Alias 와 동시에 수정해야 한다.
     */
    val alias: String
) {
    AdCode("광고코드"),
    AdType("광고구분"),
    AdName("광고명"),
    BrandId("브랜드"),
    BrandName("브랜드명"),
    PartnerName("업체명"),
    MdId("담당MD"),
    LargeCategoryCode("대분류"),
    MediumCategoryCode("중분류"),
    SmallCategoryCode("소분류"),
    LargeCategory("대분류 카테고리명"),
    MediumCategory("중분류 카테고리명"),
    SmallCategory("소분류 카테고리명"),
    CouponNumber("쿠폰번호"),
    CouponTypeDescription("쿠폰구분"),
    CouponName("쿠폰명"),
    CouponApplyType("쿠폰사용구분"),
    CouponIssueAmount("발행금액"),
    Date("date"),
    GoodsNumber("상품번호"),
    GoodsName("상품명"),
    StyleNumber("스타일넘버"),
    GoodsStatusName("상품상태"),
    PartnerId("업체코드"),
    PartnerType("업체구분"),
    SellQuantity("판매수량"),
    SellAmount("판매금액"),
    RefundQuantity("환불수량"),
    RefundAmount("환불금액"),
    ExchangeQuantity("교환수량"),
    ExchangeAmount("교환금액"),
    TradeQuantity("거래수량"),
    TradeAmount("거래금액"),
    MemberDiscounts("회원할인"),
    AffiliateDiscounts("제휴할인"),
    OtherDiscounts("기타할인"),
    CouponDiscounts("쿠폰(무신사)할인"),
    PartnerCouponDiscounts("쿠폰(업체)할인"),
    PointDiscounts("적립금할인"),
    PrePointDiscounts("선적립금할인"),
    CartDiscounts("장바구니할인"),
    GroupDiscounts("그룹할인"),
    TotalDiscounts("소계"),
    DiscountRate("할인율"),
    PaymentFees("결제수수료"),
    PaymentAmount("결제금액"),
    Sales("매출"),
    OriginalPrice("원가"),
    Profit("이익"),
    ProfitMargin("이익률"),
    PurchasesTradeAmount("매입상품_거래금액"),
    PurchasesDiscounts("매입상품_할인"),
    PurchasesPaymentFees("매입상품_결제수수료"),
    PurchasesPaymentAmount("매입상품_결제금액"),
    PurchasesOriginalPrice("매입상품_원가"),
    PurchasesProfit("매입상품_이익"),
    PurchasesProfitMargin("매입상품_이익율"),
    PurchasesRatio("매입상품_비중"),
    PartnerTradeAmount("입점상품_거래금액"),
    PartnerDiscounts("입점상품_할인"),
    PartnerPaymentFees("입점상품_결제수수료"),
    PartnerPaymentAmount("입점상품_결제금액"),
    PartnerSellFees("입점상품_판매수수료"),
    PartnerFees("입점상품_수수료"),
    PartnerSellGrants("입점상품_판매지원금"),
    PartnerProfitMargin("입점상품_이익률"),
    SalesExcludedVAT("매출(VAT별도)"),
    OriginalPriceExcludedVAT("원가(VAT별도)"),
    ProfitExcludedVAT("이익(VAT별도)"),
    ProfitMarginExcludedVAT("이익률(VAT별도)")
}
