package com.musinsa.stat.sales.dto

import java.sql.ResultSet

/**
 * 일별매출통계
 */
class Daily : SalesStatistics {
    /**
     * 8자리 일자
     * ex) 20230502
     */
    var date: String? = String()

    // JSON 역직렬화를 위해 빈 생성자 필요
    constructor()

    constructor(
        date: String?,
        isGrouping: Boolean,
        sellQuantity: Long,
        sellAmount: Long,
        refundQuantity: Long,
        refundAmount: Long,
        exchangeQuantity: Long,
        exchangeAmount: Long,
        tradeQuantity: Long,
        tradeAmount: Long,
        memberDiscounts: Long,
        affiliateDiscounts: Long,
        otherDiscounts: Long,
        couponDiscounts: Long,
        partnerCouponDiscounts: Long,
        pointDiscounts: Long,
        prePointDiscounts: Long,
        cartDiscounts: Long,
        groupDiscounts: Long,
        totalDiscounts: Long,
        discountRate: Double,
        paymentFees: Long,
        paymentAmount: Long,
        sales: Long,
        originalPrice: Long,
        profit: Long,
        profitMargin: Double,
        purchasesTradeAmount: Long,
        purchasesDiscounts: Long,
        purchasesPaymentFees: Long,
        purchasesPaymentAmount: Long,
        purchasesOriginalPrice: Long,
        purchasesProfit: Long,
        purchasesProfitMargin: Double,
        purchasesRatio: Double,
        partnerTradeAmount: Long,
        partnerDiscounts: Long,
        partnerPaymentFees: Long,
        partnerPaymentAmount: Long,
        partnerSellFees: Long,
        partnerFees: Long,
        partnerSellGrants: Long,
        partnerProfitMargin: Double,
        salesExcludedVAT: Long,
        originalPriceExcludedVAT: Long,
        profitExcludedVAT: Long,
        profitMarginExcludedVAT: Double
    ) : super(
        isGrouping,
        sellQuantity,
        sellAmount,
        refundQuantity,
        refundAmount,
        exchangeQuantity,
        exchangeAmount,
        tradeQuantity,
        tradeAmount,
        memberDiscounts,
        affiliateDiscounts,
        otherDiscounts,
        couponDiscounts,
        partnerCouponDiscounts,
        pointDiscounts,
        prePointDiscounts,
        cartDiscounts,
        groupDiscounts,
        totalDiscounts,
        discountRate,
        paymentFees,
        paymentAmount,
        sales,
        originalPrice,
        profit,
        profitMargin,
        purchasesTradeAmount,
        purchasesDiscounts,
        purchasesPaymentFees,
        purchasesPaymentAmount,
        purchasesOriginalPrice,
        purchasesProfit,
        purchasesProfitMargin,
        purchasesRatio,
        partnerTradeAmount,
        partnerDiscounts,
        partnerPaymentFees,
        partnerPaymentAmount,
        partnerSellFees,
        partnerFees,
        partnerSellGrants,
        partnerProfitMargin,
        salesExcludedVAT,
        originalPriceExcludedVAT,
        profitExcludedVAT,
        profitMarginExcludedVAT
    ) {
        this.date = date
    }

    constructor(rs: ResultSet, date: String) : this(
        date = date,
        isGrouping = rs.getBoolean("집계"),
        sellQuantity = rs.getLong("판매수량"),
        sellAmount = rs.getLong("판매금액"),
        refundQuantity = rs.getLong("환불수량"),
        refundAmount = rs.getLong("환불금액"),
        exchangeQuantity = rs.getLong("교환수량"),
        exchangeAmount = rs.getLong("교환금액"),
        tradeQuantity = rs.getLong("거래수량"),
        tradeAmount = rs.getLong("거래금액"),
        memberDiscounts = rs.getLong("회원할인"),
        affiliateDiscounts = rs.getLong("제휴할인"),
        otherDiscounts = rs.getLong("기타할인"),
        couponDiscounts = rs.getLong("쿠폰(무신사)할인"),
        partnerCouponDiscounts = rs.getLong("쿠폰(업체)할인"),
        pointDiscounts = rs.getLong("적립금할인"),
        prePointDiscounts = rs.getLong("선적립금할인"),
        cartDiscounts = rs.getLong("장바구니할인"),
        groupDiscounts = rs.getLong("그룹할인"),
        totalDiscounts = rs.getLong("소계"),
        discountRate = rs.getDouble("할인율"),
        paymentFees = rs.getLong("결제수수료"),
        paymentAmount = rs.getLong("결제금액"),
        sales = rs.getLong("매출"),
        originalPrice = rs.getLong("원가"),
        profit = rs.getLong("이익"),
        profitMargin = rs.getDouble("이익률"),
        purchasesTradeAmount = rs.getLong("매입상품_거래금액"),
        purchasesDiscounts = rs.getLong("매입상품_할인"),
        purchasesPaymentFees = rs.getLong("매입상품_결제수수료"),
        purchasesPaymentAmount = rs.getLong("매입상품_결제금액"),
        purchasesOriginalPrice = rs.getLong("매입상품_원가"),
        purchasesProfit = rs.getLong("매입상품_이익"),
        purchasesProfitMargin = rs.getDouble("매입상품_이익율"),
        purchasesRatio = rs.getDouble("매입상품_비중"),
        partnerTradeAmount = rs.getLong("입점상품_거래금액"),
        partnerDiscounts = rs.getLong("입점상품_할인"),
        partnerPaymentFees = rs.getLong("입점상품_결제수수료"),
        partnerPaymentAmount = rs.getLong("입점상품_결제금액"),
        partnerSellFees = rs.getLong("입점상품_판매수수료"),
        partnerFees = rs.getLong("입점상품_수수료"),
        partnerSellGrants = rs.getLong("입점상품_판매지원금"),
        partnerProfitMargin = rs.getDouble("입점상품_이익률"),
        salesExcludedVAT = rs.getLong("매출(VAT별도)"),
        originalPriceExcludedVAT = rs.getLong("원가(VAT별도)"),
        profitExcludedVAT = rs.getLong("이익(VAT별도)"),
        profitMarginExcludedVAT = rs.getDouble("이익률(VAT별도)")
    )
}